baseurl = "http://pharmb.io"
languageCode = "en-us"
title = "PharmBio"
theme = "pharmbio"
SectionPagesMenu = "main"
[menu]
    [[menu.main]]
    identifier = "publication"
    name       = "Publications"
    url        = "/publication/"
    [[menu.main]]
    identifier = "project"
    name       = "Projects"
    url        = "/project/"
    [[menu.main]]
    identifier = "people"
    name       = "People"
    url        = "/people/"
