baseurl = "http://pharmb.io"
languageCode = "en-us"
title = "PharmBio"
theme = "pharmbio"
SectionPagesMenu = "main"
pluralizeListTitles = false
[menu]
    [[menu.main]]
    identifier = "people"
    name       = "People"
    url        = "/people/"
    weight     = -300
    [[menu.main]]
    identifier = "publication"
    name       = "Publications"
    url        = "/publication/"
    weight     = -200
    [[menu.main]]
    identifier = "project"
    name       = "Projects"
    url        = "/project/"
    weight     = -100
    [[menu.main]]
    identifier = "tool"
    name       = "Tools"
    url        = "/tool/"
    weight     = -50
